name: Tests

on:
  push:
    branches: [ main , develop , feature/** , release/* ]

jobs:
  build:
    name: Tests
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9 # the minimum version required by the project
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Update OS
      run: sudo apt-get update
    - name: Install dependencies
      run: make install
    - name: Run Tests
      run: |
        make test-report
        make coverage_report
    - name: Upload reports
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: report.html
